[package]
name = "vector-store"
version = "0.1.0"
edition = "2021"
description = "High-performance vector storage implementation"
authors = ["Vector Store Team"]

[dependencies]
# Logging and tracing
tracing = { version = "0.1", features = ["attributes"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-appender = "0.2"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Async runtime
tokio = { version = "1.35", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Memory mapping
memmap2 = "0.9"

# Async traits
async-trait = "0.1"

# Random number generation
rand = "0.8"

# Lazy initialization
once_cell = "1.19.0"

[dev-dependencies]
criterion = "0.5"
proptest = "1.4"
test-log = "0.2"
tokio-test = "0.4"
tempfile = "3.8"

[[bench]]
name = "vector_ops"
harness = false

[[test]]
name = "integration"
path = "tests/integration/mod.rs"
