[package]
name = "vector-store"
version = "0.1.0"
edition = "2021"
description = "High-performance vector storage implementation"
authors = ["Vector Store Team"]

[dependencies]
# Logging and tracing
tracing = { version = "0.1", features = ["attributes"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-appender = "0.2"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Async runtime
tokio = { version = "1.35", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Memory mapping
memmap2 = "0.9"

# Async traits
async-trait = "0.1"

# Random number generation
rand = "0.8"
rand_distr = "0.4"

# Lazy initialization
once_cell = "1.19.0"
lazy_static = "1.4"

# Concurrency utilities
parking_lot = "0.12"
futures = "0.3"
rayon = "1.8"

# OpenTelemetry
opentelemetry = { version = "0.20" }
opentelemetry_sdk = { version = "0.20" }
opentelemetry-otlp = { version = "0.13" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
indicatif = "0.17"
colored = "2.0"
proptest = "1.4"
test-log = "0.2"
tokio-test = "0.4"
env_logger = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
plotters = "0.3"

[[bench]]
name = "main"
harness = false
path = "benches/main.rs"

[[test]]
name = "integration"
path = "tests/integration/mod.rs"
